language: python
python:
- '3.7'
services:
- docker
env:
  global:
  - GOLOOP_GIT=https://github.com/icon-project/goloop
  - GOLOOP_GIT_TAG=v0.9.5
  - secure: hf0xIHtxALX4V5T2ZixhnjIgEXH44ybgUaq3EjCHVvghbg/FtV7bYcuIalcSRsZdd2HYMcuwQXrSWHMlzZxpWega/uVJqZKt4qfsowPUxzzWDCnCFlexsEb8GVnIHlG1XYvrsd3YNML6hOtmE8M5A2zJ4tQ76RsizAxAzLVB5P1SwC/llY0pwCnSwvxXso6Pt9M0XOEXQwafVo47J5u86u8oC2mOVEXM26zXnBHUUQnIYmAIKP9E+ut1CZKG1YiJ0LqpH+vXOkvVrhJax0obKat+8Ucl9JB6rZWxN0jeg1c0pjcg6YVdv/1yWpsmycyki/GTKRjMzlWzXmpJfgvbMxYy/QVOPQJrprrJDUhs2d41JPkwTIlY7/e4P87X47bITrl2UcOybP2x337VAlLIvkMtgvxyMCvS1axj1Ad7pQh9XzkTKe16twtHdLWgFLIsePLN1nGnH5Ty7EPMAONUQgtYSZuxDMHlqrN84dEvtw0jNm4C4MAv7tKnVRSYrzHUXtzpxBXmASkNiBrsIOYRhagvdKJjZqrwvLQpy0pRA0SOqpQr8yqT91FtMQuO6PWFMeYcNrZ9PVDFloECAHH5iWrKApLqDrs57/itLagSeJYUcmvWIkC1uaA5Mk3xilGt+e2XG7IhZoF+2XYuMdHqZfHxwChhEWSzleTEXuhW4Fc=
  - secure: fFYWLkCFDSc6am27Hj8eMoY+8erpO0mcCJMD89zX460CLk2RIpRiZc0Le++2eHDR6bjwkF8V3NBh03kazpQcXVQk3aeEIVnc1caBpebeg8XE+EzSi6S6bTFKhnHu9xpxjb+LosTUj0UZ5/J7tNPdbM/l5NDSnkEu4nI1xgt7lcGgIrtsTbYljtBJJjn3PJpsEg0U3fpmkVYd7QUZq0F4BjKnq1vka+u+WwvHkTzrfCAu+xBr30sy8Hsi6IxK7hcmRufsoF+4NzZSVZuM0iKJUdeLQB+nKDCg51OwyGnNEbTcNM5pjChP4mMJosOI2A2mG2UJf5UagyEsJROXH2cjlIeIIJmLKC7DMBO3dxPnjO8oj6CVNEcvNJC5tVgRAMSju8PoxrxJN0TyGktNU1JxxRh8sNdQ0xufXy6Pa0EiWeiK/MSiiCz7oHYJVq/vqBwQJkXx/NmcV8KPdNtMooPk5dVbb5Ek2qXvteszxrDCSjCG90gOEQQoiLdzlNe/SBTG0IvB71lgxUNIoTaKyrVWH95rvP63DETT+jelwfNJphT67tIiBUEr3J9K4D67nTaO7lAA3QHQ/rxXowDhSIGiJvVDxrOi+/WpyGyyqPKkX8hVuoeMKsLp8/TBdfIZI4xyKiJ6aTfKRt/NnWmropUy5umkbNe6RexKnR4rBVrKhrI=
jobs:
  include:
  - os: linux
    arch: amd64
    env: goloop_type="goloop"
#  - os: linux
#    arch: amd64
#    env: goloop_type="gochain-icon"

branches:
  only:
  - master
before_install:
- curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
  && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64
  /usr/local/bin/container-structure-test
- 'scversion="stable" # or "v0.4.7", or "latest" wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-${scversion?}.linux.x86_64.tar.xz"
  | tar -xJv cp "shellcheck-${scversion}/shellcheck" /usr/local/bin/ shellcheck --version

'
- git clone $GOLOOP_GIT
- export TAG_NAME=$(echo "$GOLOOP_GIT_TAG" | sed 's/v//g')
install:
- cd goloop
- git checkout $GOLOOP_GIT_TAG
- make ${goloop_type}-icon-image
script:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag goloop $DOCKER_USER/${goloop_type}:$TAG_NAME
- docker tag goloop $DOCKER_USER/${goloop_type}:latest
- docker push $DOCKER_USER/${goloop_type}:$TAG_NAME
- docker push $DOCKER_USER/${goloop_type}:latest
